package pers.kksg.demo.utils;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;

/**
 * @project: demo
 * @description:
 * @author: lvqiang
 * @create: 2025-07-30 15:44
 **/
public class JsonUtil {

    /**
     * 将 JSON 字符串的 key 按字典序排序
     * @param jsonString 输入的 JSON 字符串
     * @return 排序后的 JSON 字符串
     * @throws Exception 解析错误时抛出异常
     */
    public static String sortJsonKeys(String jsonString) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.enable(SerializationFeature.INDENT_OUTPUT);

        JsonNode jsonNode = objectMapper.readTree(jsonString);
        JsonNode sortedNode = sortJsonNode(jsonNode);

        return objectMapper.writeValueAsString(sortedNode);
    }

    // 递归处理 JSON 节点
    private static JsonNode sortJsonNode(JsonNode node) {
        if (node.isObject()) {
            // 创建排序好的 TreeMap
            Map<String, JsonNode> sortedMap = new TreeMap<>();
            Iterator<Map.Entry<String, JsonNode>> fields = node.fields();

            while (fields.hasNext()) {
                Map.Entry<String, JsonNode> field = fields.next();
                sortedMap.put(field.getKey(), sortJsonNode(field.getValue()));
            }

            // 构建新对象
            ObjectNode sortedObject = JsonNodeFactory.instance.objectNode();
            sortedMap.forEach(sortedObject::set);

            return sortedObject;
        } else if (node.isArray()) {
            ArrayNode sortedArray = JsonNodeFactory.instance.arrayNode();

            for (JsonNode element : node) {
                sortedArray.add(sortJsonNode(element));
            }

            return sortedArray;
        } else {
            // 基础类型直接返回
            return node;
        }
    }

    public static void main(String[] args) {
        String json = "{\"control\":{\"alias\":\"APR_TX4\",\"daerrmsg\":\"DS10\",\"edition\":\"5\",\"editiondate\":\"20250731\",\"errmessage\":\"\",\"errorcount\":\"5\",\"inputdataarea\":\"IN\",\"objective\":\"APR_TX4\",\"outputdataarea\":\"OUT\",\"returncode\":43,\"signature\":\"EXPERIAN\",\"systemdate\":\"20250810\",\"tracelevel\":\"0\"},\"inputFields\":{\"PPCM_M1_NBANK_FIN_SUCC_REPNUM\":6.0,\"XY_M0UP_OVERDUE_CNT_L12M_I\":1.0,\"PPCM_M1_SUCC_REPORG\":5.0,\"AVG_APPLY_CREDIT_RATIO_6M_F\":0.942,\"TC_PAYMENT_SCORE_G003_F\":461.0,\"XY_LOAN_AMT_L12M_I\":6.0,\"XY_LOANAMT_UP10K_L12M_CNT_I\":0.0,\"PPCM_M12_QY_REP_RATIO\":3.7,\"XY_LOAN_ORG_L3M_I\":0.0,\"PPCM_M6_SUCC_REPAMT_MAX\":5.0,\"XHBL_FLAG\":0.0,\"XY_OVERDUE_LASTDAY_I\":6.0,\"XY_PAYED_CNT_I\":5.0,\"PPCM_D7_NBANK_FIN_SUCC_REPORG\":-1.0,\"PPCM_M3_SUCC_REPAMT_MAX\":5.0,\"SETTLE_CREDIT_MAX_F\":7360.0,\"XY_OVERDUE_AMT_L24M_I\":5.0,\"XY_INQUERY_CNT_L3M_I\":15.0,\"BR_BLACK_SL_ID_M36_ALL_RISK_ORGNUM\":-99998.0,\"BR_BLACK_SL_ID_M12_ABNORMAL_CNT\":-99998.0,\"PPCM_D7_FAIL_REPAMT_MAX\":-1.0,\"XY_CONSUMEFINANCE_PRODUCT_I\":6.0,\"XY_LATEST_QUERY_TIME_S\":\"202507\",\"XY_OVERDUE_AMT_L12M_I\":2.0,\"BR_BLACK_SL_ID_M36_COURT_EXECUTED\":-99998.0,\"XY_LOAN_AMT_L24M_I\":7.0,\"PPCM_M12_SUCC_REPAMT_MAX\":5.0,\"SETTLE_LOGIN_WORKTIME_M6_I\":2.0,\"BR_BLACK_SL_CELL_M6_ABNORMAL_CNT\":-99998.0,\"CONTRACT_N_6_I\":1.0,\"PPCM_M1_M6_BANK_QYNUM_RATIO\":0.0,\"PPCM_M3_NBANK_FIN_NEH_REPNUM_RATIO\":0.63,\"XY_INTERNETLEND_CONFI_F\":85.0,\"XY_LOAN_CNT_L3M_I\":0.0,\"BR_BLACK_SL_ID_M36_ALL_RISK_CNT\":-99998.0,\"XY_INTERNETLEND_CRED_I\":700.0,\"XY_OVERDUEA_AMT_L12M_I\":1.0,\"BEHAVIOR_SUB_SCORE2_F\":-99998.0,\"BR_BLACK_SL_CELL_M36_REJ_HIGH_RISK\":-99998.0,\"PPCM_M3_BANK_NEH_REPNUM_RATIO\":-1.0,\"PPCM_M1_NBANK_FIN_SUCC_REPAMT\":7.0,\"XY_LOAN_BEHAVIOR_I\":482.0,\"SETTLE_CUR_FIRST_DIFF_DAYS_I\":103.0,\"BR_BLACK_SL_ID_M6_NBANK_RISK\":-99998.0,\"XY_NOROVERDUE_PCT_I\":0.64,\"PPCM_M1_NBANK_FIN_LOANAMT\":-1.0,\"PPCM_M12_NBANK_FIN_LOANAMT\":-1.0,\"XY_CONSUMEFINANCE_ORG_L12M_I\":2.0,\"BR_BLACK_SL_CELL_M6_NBANK_RISK\":-99998.0,\"XY_OVERDUE_CNT_L3M_I\":0.0,\"BR_BLACK_SL_CELL_M6_NBANK_OVERDUE\":-99998.0,\"XY_CREDIT_DAY_I\":720.0,\"BR_BLACK_SL_CELL_M36_BANK_OVERDUE\":-99998.0,\"BR_BLACK_SL_ID_M36_NBANK_OVERDUE\":-99998.0,\"BR_BLACK_SL_ID_M36_REJ_HIGH_RISK\":-99998.0,\"XY_CONSUMEFINANCE_AVGCREDIT_I\":5800.0,\"PPCM_M3_NBANK_FIN_LOANAMT\":-1.0,\"PPCM_M1_M6_NBANK_OTHER_QYNUM_RATIO\":0.09,\"BR_BLACK_SL_CELL_M36_ALL_RISK_ORGNUM\":-99998.0,\"XY_QUERY_SUM_COUNT_I\":73.0,\"BR_BLACK_SL_ID_M36_NBANK_RISK\":-99998.0,\"PPCM_D7_REPORG\":-1.0,\"XY_LOAN_CNT_L12M_I\":2.0,\"XY_LOANBEH_CONFI_F\":85.0,\"XY_M1UP_OVERDUE_CNT_L6M_I\":0.0,\"XY_LOANAMT_3_10K_L12M_CNT_I\":1.0,\"YM_SAFETY_UNBANK_SCORE_F\":0.439852,\"BR_BLACK_SL_CELL_M36_BANK_RISK\":-99998.0,\"XY_FAIL_REPAY_CNT_L6M_I\":8.0,\"XY_CONSUMEFINANCE_CONFI_F\":85.0,\"PPCM_D7_NBANK_FIN_QYNUM\":-1.0,\"BR_BLACK_SL_ID_M6_BANK_RISK\":-99998.0,\"PPCM_D7_BANK_SUCC_REPAMT\":-1.0,\"BF_SE_PASS_MTH_CNT_IN_12M_I\":1.0,\"XY_CONSUMEFINANCE_MAXCREDIT_I\":7800.0,\"BR_BLACK_SL_CELL_M12_BANK_OVERDUE\":-99998.0,\"SETTLE_LOGIN_EVENING_M6_I\":7.0,\"BR_BLACK_SL_CELL_M6_BANK_BAD\":-99998.0,\"XY_INTERNETLEND_ORG_L12M_I\":0.0,\"PPCM_M3_NBANK_FIN_SUCC_REPAMT\":12.0,\"PPCM_M1_NBANK_FIN_NEH_REPNUM_RATIO\":0.4,\"XY_FAIL_REPAY_CNT_L1M_I\":0.0,\"XY_OVERDUE_CNT_L1M_I\":0.0,\"BR_BLACK_SL_CELL_M36_ALL_RISK_CNT\":-99998.0,\"PPCM_M6_NBANK_FIN_LOANAMT\":-1.0,\"PPCM_M1_M24_BANK_FAIL_REPNUM_RATIO\":0.0,\"XY_LOAN_CNT_L24M_I\":11.0,\"PPCM_M6_NBANK_FIN_SUCC_REPORG\":5.0,\"XY_LOAN_ORG_L12M_I\":2.0,\"BF_SE_PASS_MTH_RATIO_IN_6M_F\":0.0,\"EARLY_N_6_I\":0.0,\"PPCM_M24_FAIL_NEH_REPNUM_RATIO\":0.61,\"PPCM_M24_BANK_SUCC_REPAMT\":19.0,\"PPCM_M1_QY_REP_RATIO\":5.0,\"XY_LOAN_AMT_L3M_I\":0.0,\"MOB_I\":27.0,\"XY_M0UP_OVERDUE_CNT_L24M_I\":2.0,\"PPCM_M3_OVERNUM\":6.0,\"PPCM_M1_NBANK_OTHER_NEH_REPNUM_RATIO\":-1.0,\"XY_INTERNETLEND_ORG_I\":1.0,\"PPCM_M6_M24_FAIL_REPNUM_RATIO\":0.41,\"BR_BLACK_SL_CELL_M36_NBANK_BAD\":-99998.0,\"BF_SE_PASS_MTH_CNT_IN_24M_I\":2.0,\"BR_BLACK_SL_ID_M12_NBANK_OVERDUE\":-99998.0,\"PPCM_M12_NBANK_FIN_NEH_REPNUM_RATIO\":0.6,\"BR_BLACK_SL_ID_M12_BANK_RISK\":-99998.0,\"SETTLE_LOAN_CNT_M6_I\":0.0,\"AGE\":36,\"BR_BLACK_FLAG_SPECIALLIST_C\":-99998.0,\"PPCM_M3_NBANK_FIN_SUCC_REPNUM\":14.0,\"BR_BLACK_SL_CELL_M12_BANK_BAD\":-99998.0,\"BR_BLACK_SL_CELL_M6_BANK_RISK\":-99998.0,\"PPCM_M3_SUCC_REPAMT\":12.0,\"PPCM_M1_M6_NBANK_FIN_QYNUM_RATIO\":0.17,\"PPCM_M24_NBANK_FIN_NEH_REPNUM_RATIO\":0.59,\"DXM_XM_INCOME_LEVEL_12_V3_I\":9.0,\"PPCM_M12_NBANK_FIN_SUCC_REPNUM\":62.0,\"XY_LOAN_ORG_L24M_I\":4.0,\"CURR_OVERDUE_DAYS_I\":0.0,\"BR_BLACK_SL_CELL_M12_NBANK_BAD\":-99998.0,\"XY_LOAN_CNT_L1M_I\":0.0,\"PPCM_M3_M24_FAIL_REPNUM_RATIO\":0.19,\"BR_BLACK_SL_CELL_M6_ABNORMAL_ORGNUM\":-99998.0,\"PPCM_M3_FAIL_NEH_REPNUM_RATIO\":0.62,\"PPCM_M1_BANK_SUCC_REPAMT\":-1.0,\"PPCM_M1_FAIL_REPORG_NEW\":1.0,\"PPCM_M3_M24_BANK_QYNUM_RATIO\":0.09,\"SETTLE_CONTRACT_N_3_I\":3.0,\"DXM_DQ_VIP_SCORE_V3_F\":0.2866,\"BR_BLACK_SL_ID_M36_BANK_RISK\":-99998.0,\"PPCM_M1_M24_FAIL_REPNUM_RATIO\":0.03,\"PPCM_BEHAV_SCORE\":627.0,\"BR_BLACK_SL_CELL_M12_NBANK_OVERDUE\":-99998.0,\"XY_QUERY_CASH_COUNT_I\":5.0,\"DXM_PHONE_TMP_LIST_S\":\"\",\"BR_BLACK_SL_CELL_FLAG\":-99998.0,\"TOTAL_CREDIT_F\":7360.0,\"BR_BLACK_SL_ID_M12_NBANK_RISK\":-99998.0,\"XY_INTERNETLEND_AVGCREDIT_I\":700.0,\"BR_BLACK_SL_ID_M6_ALL_RISK_ORGNUM\":-99998.0,\"BR_BLACK_SL_CELL_M6_BANK_OVERDUE\":-99998.0,\"XY_LOAN_ORG_L6M_I\":0.0,\"PPCM_M6_NBANK_FIN_QYNUM\":6.0,\"MAYI_ZZ26_F\":0.38060635,\"PPCM_D7_NBANK_FIN_SUCC_REPAMT\":-1.0,\"BR_BLACK_SL_ID_M6_ABNORMAL_CNT\":-99998.0,\"PPCM_M12_LOANNUM\":-1.0,\"XY_INQUERY_CNT_L6M_I\":34.0,\"XY_OVERDUE_CNT_L6M_I\":2.0,\"XY_M0UP_OVERDUE_CNT_L6M_I\":0.0,\"PPCM_M12_FAIL_NEH_REPNUM_RATIO\":0.64,\"PPCM_LATEST_REP_STATUS\":2.0,\"XY_INTERNETLEND_ORG_L24M_I\":1.0,\"XY_OVERDUE_AMT_L6M_I\":1.0,\"PPCM_M1_M24_NBANK_OTHER_FAIL_REPNUM_RATIO\":0.0,\"PPCM_M3_NBANK_OTHER_NEH_REPNUM_RATIO\":0.0,\"BR_BLACK_SL_CELL_M36_NBANK_OVERDUE\":-99998.0,\"PPCM_M1_FAIL_NEH_REPNUM_RATIO\":0.4,\"PPCM_M12_NBANK_FIN_SUCC_REPORG\":5.0,\"LK_91666_SCORE_F\":62.0,\"TOTAL_CREDIT_USED_RATE_F\":0.0,\"TC_BLACK_A_I\":1.0,\"PPCM_M1_FAIL_REPNUM\":4.0,\"XY_LOAN_CNT_L6M_I\":0.0,\"XY_OVERDUE_AMT_L1M_I\":0.0,\"XY_QUERY_FINANCE_COUNT_I\":15.0,\"UM_UNBANKPRO_F\":0.193758,\"PPCM_M1_M24_NBANK_FIN_FAIL_REPNUM_RATIO\":0.04,\"PPCM_M3_CRED_REPORG_NEW\":-1.0,\"BR_BLACK_SL_IS_HIGH_RISK\":-99998.0,\"XY_FAIL_REPAY_CNT_L12M_I\":28.0,\"HX_SCORE1\":90.0,\"PPCM_M6_QYDAY\":17.0,\"BR_BLACK_SL_ID_M6_ABNORMAL_ORGNUM\":-99998.0,\"BR_BLACK_SL_ID_M6_BANK_OVERDUE\":-99998.0,\"BR_BLACK_SL_ID_M12_BANK_BAD\":-99998.0,\"BR_BLACK_SL_CELL_M12_ALL_RISK_ORGNUM\":-99998.0,\"XY_OVERDUE_CNT_L24M_I\":11.0,\"XY_LOAN_AMT_L1M_I\":0.0,\"BR_BLACK_SL_ID_M36_BANK_BAD\":-99998.0,\"XY_APPLY_SCORE_I\":506.0,\"SETTLE_LOAN_CNT_M3_I\":0.0,\"XY_OVERDUEA_AMT_L24M_I\":1.0,\"PPCM_M12_SUCC_REPAMT\":19.0,\"HX_SCORE3\":66.0,\"SETTLE_DATE_REPAYED_AMOUNT_12M_F\":9184.1,\"XY_LOAN_AMT_L6M_I\":0.0,\"BR_BLACK_SL_CELL_M36_ABNORMAL_ORGNUM\":-99998.0,\"BR_BLACK_SL_ID_M6_BANK_BAD\":-99998.0,\"PPCM_M6_NBANK_FIN_NEH_REPNUM_RATIO\":0.57,\"AF_RESULT_I\":-99998.0,\"BR_BLACK_SL_ID_M6_COURT_BAD\":-99998.0,\"XY_OVERDUE_AMT_L3M_I\":0.0,\"PPCM_D7_NBANK_OTHER_QYNUM\":-1.0,\"XY_LOANAMT_LOW1K_L12M_CNT_I\":1.0,\"XY_LOANAMT_1_3K_L12M_CNT_I\":0.0,\"XY_M1UP_OVERDUE_CNT_L24M_I\":0.0,\"BR_BLACK_SL_ID_M12_ALL_RISK_ORGNUM\":-99998.0,\"PPCM_M1_NBANK_OTHER_SUCC_REPNUM\":-1.0,\"PPCM_M1_OVERNUM\":1.0,\"XY_OVERDUEA_AMT_L6M_I\":0.0,\"XY_CONSFIN_CRED_I\":4100.0,\"XY_INTERNETLEND_PRODUCT_I\":2.0,\"CONTRACT_N_3_I\":-99998.0,\"PPCM_D7_NBANK_OTHER_SUCC_REPORG\":-1.0,\"XY_FAIL_REPAY_CNT_L24M_I\":36.0,\"BR_BLACK_SL_ID_M36_ABNORMAL_ORGNUM\":-99998.0,\"PPCM_M3_NBANK_OTHER_QYORG\":11.0,\"PPCM_M24_NBANK_FIN_SUCC_REPORG\":5.0,\"XY_CONSUMEFINANCE_ORG_I\":3.0,\"XY_LOAN_ORG_L1M_I\":0.0,\"BR_BLACK_SL_CELL_M12_ABNORMAL_ORGNUM\":-99998.0,\"SETTLE_CONTRACT_N_6_I\":6.0,\"XY_OVERDUE_CNT_L12M_I\":5.0,\"BR_BLACK_SL_ID_M12_ABNORMAL_ORGNUM\":-99998.0,\"PPCM_M24_BANK_LOANAMT\":-1.0,\"PPCM_D7_FAIL_REPNUM\":-1.0,\"XY_FAIL_REPAY_CNT_L3M_I\":0.0,\"PPCM_M6_FAIL_NEH_REPNUM_RATIO\":0.59,\"XY_CONSUMEFINANCE_ORG_L24M_I\":3.0,\"PPCM_D7_NBANK_OTHER_NEH_REPNUM_RATIO\":-1.0,\"SETTLE_CURRENTDATE_DIFF_DAYS_I\":168.0,\"XY_INQUERY_CNT_L1M_I\":3.0,\"XY_APPLY_CONFI_F\":74.0,\"XY_INTERNETLEND_MAXCREDIT_I\":700.0,\"PPCM_M6_BANK_NEH_REPNUM_RATIO\":0.75,\"PPCM_M3_SUCC_REPNUM_AVG\":5.0,\"SSN_PROVINCE_S\":\"广西省\",\"XY_M1UP_OVERDUE_CNT_L12M_I\":0.0,\"PPCM_M6_SUCC_REPAMT\":19.0,\"XY_LOAN_LASTDAY_I\":9.0,\"XY_QUERY_ORG_COUNT_I\":30.0,\"BR_BLACK_SL_ID_M36_COURT_BAD\":-99998.0,\"BR_BLACK_SL_CELL_M36_BANK_BAD\":-99998.0},\"outputFields\":{\"REJ_CODE_S[18]\":\"\",\"REJ_DESC_S[6]\":\"\",\"REJ_IND_S[9]\":\"\",\"SPECIAL_MARK_F[4]\":-99999.0,\"REJ_CODE_S[14]\":\"\",\"SPECIAL_MARK_S[6]\":\"\",\"REJ_DESC_S[2]\":\"\",\"REJ_IND_S[5]\":\"\",\"SPECIAL_MARK_S[10]\":\"\",\"REJ_DESC_S[17]\":\"\",\"SPECIAL_MARK_F[8]\":-99999.0,\"REJ_CODE_S[10]\":\"\",\"SPECIAL_MARK_S[2]\":\"\",\"PPCM_MODEL_V3_I\":512.0,\"REJ_IND_S[1]\":\"\",\"PPCM_MODEL_V1_I\":641.0,\"REJ_DESC_S[13]\":\"\",\"REJ_CODE_S[9]\":\"\",\"REJ_IND_S[17]\":\"\",\"RESULT_S\":\"PASS\",\"SPECIAL_MARK_S[1]\":\"\",\"REJ_CODE_S[1]\":\"\",\"REJ_CODE_S[5]\":\"\",\"REJ_IND_S[13]\":\"\",\"SPECIAL_MARK_F[1]\":-99999.0,\"REJ_DESC_S[9]\":\"\",\"SPECIAL_MARK_F[5]\":-99999.0,\"REJ_CODE_S[17]\":\"\",\"REJ_DESC_S[5]\":\"\",\"REJ_IND_S[8]\":\"\",\"REJ_DESC_S[16]\":\"\",\"SPECIAL_MARK_F[9]\":-99999.0,\"REJ_CODE_S[13]\":\"\",\"SPECIAL_MARK_S[7]\":\"\",\"REJ_DESC_S[1]\":\"\",\"REJ_IND_S[4]\":\"\",\"REJ_DESC_S[12]\":\"\",\"SPECIAL_MARK_S[3]\":\"\",\"APP_RESULT_1ST_OUT_I\":1.0,\"REJ_CODE_S[8]\":\"\",\"REJ_IND_S[18]\":\"\",\"REJ_DESC_S[20]\":\"\",\"REJ_IND_S[10]\":\"\",\"REJ_CODE_S[4]\":\"\",\"REJ_IND_S[14]\":\"\",\"CUSTORMER_GRADE_S\":\"E\",\"SPECIAL_MARK_F[2]\":-99999.0,\"REJ_DESC_S[8]\":\"\",\"REJ_IND_S[7]\":\"\",\"REJ_DESC_S[19]\":\"\",\"SPECIAL_MARK_F[6]\":-99999.0,\"REJ_CODE_S[16]\":\"\",\"REJ_DESC_S[4]\":\"\",\"REJ_IND_S[3]\":\"\",\"REJ_DESC_S[15]\":\"\",\"REJ_CODE_S[12]\":\"\",\"SPECIAL_MARK_S[8]\":\"\",\"REJ_DESC_S[11]\":\"\",\"REJ_CODE_S[20]\":\"\",\"SPECIAL_MARK_S[4]\":\"\",\"PPCM_MODEL_V2_I\":478.0,\"REJ_IND_S[19]\":\"\",\"REJ_CODE_S[3]\":\"\",\"REJ_IND_S[11]\":\"\",\"REJ_CODE_S[7]\":\"\",\"REJ_IND_S[15]\":\"\",\"REJ_CODE_S[19]\":\"\",\"REJ_DESC_S[7]\":\"\",\"REJ_IND_S[6]\":\"\",\"SPECIAL_MARK_F[3]\":-99999.0,\"REJ_CODE_S[15]\":\"\",\"REJ_DESC_S[3]\":\"\",\"REJ_IND_S[2]\":\"\",\"REJ_DESC_S[18]\":\"\",\"SPECIAL_MARK_F[7]\":-99999.0,\"REJ_CODE_S[11]\":\"\",\"SPECIAL_MARK_S[9]\":\"\",\"REJ_DESC_S[14]\":\"\",\"SPECIAL_MARK_S[5]\":\"\",\"REJ_DESC_S[10]\":\"\",\"SPECIAL_MARK_F[10]\":-99999.0,\"REJ_CODE_S[2]\":\"\",\"REJ_IND_S[12]\":\"\",\"REJ_IND_S[20]\":\"\",\"REJ_CODE_S[6]\":\"\",\"REJ_IND_S[16]\":\"\"},\"process\":{},\"resultCode\":\"43\",\"resultFlag\":false,\"resultMsg\":\"决策引擎异常信息代码：DS10\",\"resultMsgEnum\":\"FAILURE_RESPONSE\"}\n";

        try {
            String sortedJson = sortJsonKeys(json);
            System.out.println("Sorted JSON:");
            System.out.println(sortedJson);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
